import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NewNavbar from "./navbar";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NewNavbar />
        <main className="min-h-[100vh]">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
